version: '3'
services:
  # External Supplier .Net
  ext:
    build: ./dotnet
    image: supplier
    container_name: supplier
    expose:
      - "9090"
    # ports:
    #   - "9090:9090"
    networks:
      - backend

  # VueJS Client app
  vue:
    build: ./client
    image: vue
    container_name: vue
    ports:
          - "8844:8844"
    expose:
          - "8844"
    volumes:
        - ./client/:/vuejs_client
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    networks:
      - frontend
      - default

  # J2E Backend
  backend:
    build: ./Livrair
    image: backend
    container_name: backend
    environment:
      - supplier_host=supplier
      - supplier_port=9090
    expose:
      - "8080"
    ports:
      - "8080:8080"
    depends_on:
      - ext
    networks:
      - backend
      - frontend

networks:
  frontend:

  backend:

