version: '3'
services:
  # External Supplier .Net
  ext:
    build: ./dotnet
    container_name: supplier
    expose:
      - "9090"
    ports:
      - "9090:9090"

  # Clien Java CLI
  client:
    build: ./client
    container_name: client
#    depends_on:
#      - backend
#    ports:
#      - "8080:8080"
#    command: "host.docker.internal 8080"
    command: "backend 8080"
#    volumes:
#      - .:/host
    stdin_open: true
    tty: true

  backend:
    build: ./Livrair
    container_name: backend
    environment:
      - supplier_host=supplier
      - supplier_port=9090
    expose:
      - "8080"
    ports:
      - "8080:8080"
    depends_on:
      - ext
