version: '3'
services:
  # External Supplier .Net
  ext:
    build: ./dotnet
    container_name: supplier
    expose:
      - "9090"
#    ports:
#      - "9090:9090"
    networks:
      - backend

  vue:
    build: ./client
    container_name: vue
    ports:
          - "8844:8844"
    expose:
          - "8844"
    volumes:
        - ./client/:/vuejs_client
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    networks:
      - frontend
      - default

  backend:
    build: ./Livrair
    container_name: backend
    environment:
      - supplier_host=supplier
      - supplier_port=9090
    expose:
      - "8080"
    ports:
      - "8080:8080"
    depends_on:
      - ext
    networks:
      - backend
      - frontend

networks:
  frontend:
    # Use a custom driver
#    driver: custom-driver-1
  backend:
    # Use a custom driver which takes special options
#    driver: custom-driver-2
#    driver_opts:
#      foo: "1"
