FROM jenkins/jenkins:lts

# Derived from https://github.com/getintodevops/jenkins-withdocker (miiro@getintodevops.com)

USER root

    # First docker compose
RUN   curl -L "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && \
   chmod +x /usr/local/bin/docker-compose && \
   apt-get update && \

   # Then Docker
   apt-get -y --no-install-recommends install apt-transport-https \
         ca-certificates \
         curl \
         gnupg2 \
         software-properties-common && \
       curl -fsSL https://download.docker.com/linux/$(. /etc/os-release; echo "$ID")/gpg > /tmp/dkey; apt-key add /tmp/dkey && \
       add-apt-repository \
         "deb [arch=amd64] https://download.docker.com/linux/$(. /etc/os-release; echo "$ID") \
         $(lsb_release -cs) \
         stable" && \
      apt-get update && \
      apt-get -y --no-install-recommends install docker-ce && \

   # Cypress dependecies
   apt-get install libgtk2.0-0 libgtk-3-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb && \

   # NPM
    curl -sL https://deb.nodesource.com/setup_13.x | bash - && \
    apt-get install -y nodejs && \

   apt-get clean && \

   # Mono
   apt install apt-transport-https dirmngr gnupg ca-certificates && \
   apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF && \
   echo "deb https://download.mono-project.com/repo/debian stable-stretch main" | tee /etc/apt/sources.list.d/mono-official-stable.list && \
   apt update && \
   apt install mono-devel

#   apt-get clean && \
#   usermod -aG docker jenkins

# drop back to the regular jenkins user - good practice
#USER jenkins
