#!/bin/bash
echo "------------------------------------------"
echo "Jenkins external server"
echo "URL : http://dev.richard-peres.com:8181/"
echo "Username : admin"
echo "Password : Drone_Delivery69"
echo "Commentaire : Nous avons créé une image Jenkins spéciale pour ce projet étant donné que nous devions installer plusieurs outils (comme Mono, NPM et Cypress) sur l'host pour pouvoir faire fonctionner nos builds plans correctement."
echo "------------------------------------------"
echo ""
echo "------------------------------------------"
echo "Artifactory external server"
echo "URL : http://dev.richard-peres.com:8082"
echo "Username : admin"
echo "Password : Drone_Delivery69"
echo "------------------------------------------"
