package fr.unice.polytech.si._4a.isa.drone_delivery.delivery;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.10
<<<<<<< HEAD
 * 2020-03-19T17:06:41.423+01:00
=======
 * 2020-03-19T18:32:39.422+01:00
>>>>>>> 66b562d4b66e9a50681c131f8785fa1ad8d43c05
 * Generated source version: 3.1.10
 * 
 */
@WebServiceClient(name = "DeliveryWebServiceImplService", 
<<<<<<< HEAD
                  wsdlLocation = "file:/C:/Users/sylma/Desktop/projet-isa-devops-20-team-f-20/client/src/main/resources/DeliveryWebServiceImpl.wsdl",
=======
                  wsdlLocation = "file:/C:/Users/pa2a/OneDrive/Documents/Polytech/SI4%20-%20S8/ISA-DevOps/projet-isa-devops-20-team-f-20/client/src/main/resources/DeliveryWebServiceImpl.wsdl",
>>>>>>> 66b562d4b66e9a50681c131f8785fa1ad8d43c05
                  targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/drone-delivery/delivery") 
public class DeliveryWebServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.polytech.unice.fr/si/4a/isa/drone-delivery/delivery", "DeliveryWebServiceImplService");
    public final static QName DeliveryWebServiceImplPort = new QName("http://www.polytech.unice.fr/si/4a/isa/drone-delivery/delivery", "DeliveryWebServiceImplPort");
    static {
        URL url = null;
        try {
<<<<<<< HEAD
            url = new URL("file:/C:/Users/sylma/Desktop/projet-isa-devops-20-team-f-20/client/src/main/resources/DeliveryWebServiceImpl.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DeliveryWebServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/sylma/Desktop/projet-isa-devops-20-team-f-20/client/src/main/resources/DeliveryWebServiceImpl.wsdl");
=======
            url = new URL("file:/C:/Users/pa2a/OneDrive/Documents/Polytech/SI4%20-%20S8/ISA-DevOps/projet-isa-devops-20-team-f-20/client/src/main/resources/DeliveryWebServiceImpl.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DeliveryWebServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/pa2a/OneDrive/Documents/Polytech/SI4%20-%20S8/ISA-DevOps/projet-isa-devops-20-team-f-20/client/src/main/resources/DeliveryWebServiceImpl.wsdl");
>>>>>>> 66b562d4b66e9a50681c131f8785fa1ad8d43c05
        }
        WSDL_LOCATION = url;
    }

    public DeliveryWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DeliveryWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DeliveryWebServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public DeliveryWebServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public DeliveryWebServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public DeliveryWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns DeliveryWebService
     */
    @WebEndpoint(name = "DeliveryWebServiceImplPort")
    public DeliveryWebService getDeliveryWebServiceImplPort() {
        return super.getPort(DeliveryWebServiceImplPort, DeliveryWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DeliveryWebService
     */
    @WebEndpoint(name = "DeliveryWebServiceImplPort")
    public DeliveryWebService getDeliveryWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(DeliveryWebServiceImplPort, DeliveryWebService.class, features);
    }

}
