package fr.unice.polytech.si._4a.isa.drone_delivery.delivery;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2020-03-19T17:06:41.394+01:00
 * Generated source version: 3.1.10
 * 
 */
@WebService(targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/drone-delivery/delivery", name = "DeliveryWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface DeliveryWebService {

    @WebMethod
    @RequestWrapper(localName = "getPackageById", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/drone-delivery/delivery", className = "fr.unice.polytech.si._4a.isa.drone_delivery.delivery.GetPackageById")
    @ResponseWrapper(localName = "getPackageByIdResponse", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/drone-delivery/delivery", className = "fr.unice.polytech.si._4a.isa.drone_delivery.delivery.GetPackageByIdResponse")
    @WebResult(name = "matching_package", targetNamespace = "")
    public fr.unice.polytech.si._4a.isa.drone_delivery.delivery.Package getPackageById(
        @WebParam(name = "id", targetNamespace = "")
        java.lang.String id
    );
}
